#!/bin/bash
# PreToolUse hook for Edit|Write|NotebookEdit: block edits to secrets and
# generated files, and require confirmation for deploy config.
path=$(jq -r '.tool_input.file_path // .tool_input.notebook_path // empty')
[ -z "$path" ] && exit 0
rel=${path#"${CLAUDE_PROJECT_DIR:-$PWD}"/}

decide() {
  jq -n --arg d "$1" --arg r "$2" \
    '{hookSpecificOutput: {hookEventName: "PreToolUse", permissionDecision: $d, permissionDecisionReason: $r}}'
  exit 0
}

case "$rel" in
  .env | .env.* | */.env | */.env.*)
    decide deny "$rel holds environment config; ask the user to edit it themselves." ;;
  package-lock.json)
    decide deny "package-lock.json is generated; change dependencies with npm install instead." ;;
  amplify/* | src/aws-exports.js | src/amplifyconfiguration.json)
    decide deny "$rel is generated by the Amplify CLI; don't hand-edit it." ;;
  build/* | node_modules/*)
    decide deny "$rel is build output / installed dependencies; don't hand-edit it." ;;
  amplify.yml)
    decide ask "amplify.yml controls the production build and security headers (CSP); confirm this change." ;;
esac
exit 0
